BBMASK .= "|meta-rdk-broadband/recipes-extended/hwselftest/"
BBMASK .= "|meta-rdk-broadband/recipes-thirdparty/opensync-headers/"

BBMASK .= "|meta-rdk/recipes-common/nlmonitor/"
BBMASK .= "|meta-rdk/recipes-common/sys_mon_tools/cpuprocanalyzer_git.bb"
BBMASK .= "|meta-rdk/recipes-connectivity/bluetooth/"

BBMASK .= "|meta-cmf-raspberrypi/recipes-extended/wifi-client-hal/"

BBMASK .= "|meta-cmf/recipes-extended/rpcserver/"
